[env:esp32dev_cable]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson @ ^7.0.4

; Perfil de Upload Sem Fio (OTA)
[env:esp32dev_ota]
extends = env:esp32dev_cable
upload_protocol = espota
upload_port = monitorpoco.local
upload_flags =
    --port=3232
